on: [push, pull_request]
name: linting & code quality
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
       args: --config=.project.php_cs --diff
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
       commit_message: Apply php-cs-fixer changes
    - name: Notify chatops
      uses: sarisia/actions-status-discord@v1
       if: always()
       with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "Github actions linting"
        description: "Test notification"
        username: Github Actions
        avatar_url: ${{ secrets.AVATAR_URL }}

